### ISSUE TITLE
小鱼易连NE60 /80 如何安装语音助手

### ISSUE THREAD

**Issue by dukoalad** [xylink-com/xylink-rtc-electron-demo#20]
1.之前使用过小鱼在家，语音命令【给某某打电话】挺实用，请问小鱼易连如何刷机或者安装语音助手；
2.终端NE60 /80 呼叫用户app端，无法主动呼起，如何开启。

**Comment by luojinghui** [comment]
> 

可以通过小鱼客户端呼叫188188号码咨询客服；

小鱼客户端下载地址：https://xylink.com/download
